const users = [
    {
        id:'1',
        fname:'Allern',
        lname:'Wilson',
        email:'allern@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'2',
        fname:'David',
        lname:'Wiliam',
        email:'david@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'3',
        fname:'Robert',
        lname:'Perera',
        email:'robert@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'4',
        fname:'Mick',
        lname:'Jakson',
        email:'mick@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'5',
        fname:'Rocky',
        lname:'Bhai',
        email:'rocky@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'6',
        fname:'Fathima',
        lname:'nashrudeen',
        email:'fathima@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'7',
        fname:'Ann',
        lname:'Rodrigu',
        email:'ann@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'8',
        fname:'Amal',
        lname:'Kamalathissa',
        email:'amal@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    },
    {
        id:'9',
        fname:'Sami',
        lname:'Fernando',
        email:'sami@gmail.com',
        image:'https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png'
    }
];

export default users;